/// A `get_production_round` payload shaped exactly like the fixed contract
/// (`.scratch/production-round/CONTRACT.md`).
///
/// Numbers are deliberately mixed ints and doubles — the server sends `76.0`
/// for one field and `139` for the next — and one `days_of_cover` is null.
Map<String, dynamic> productionRoundFixture() => {
  'generated_on': '2026-09-23 18:00:00',
  'company': 'Jarz',
  'source_warehouse': 'Finished Goods - J',
  'cycle_days': 14,
  'backup_days': 7,
  'cover_days': 21,
  'sales_weeks': 8,
  'sales_from': '2026-07-29',
  'sales_to': '2026-09-22',
  'batch_sizes': {'Medium': 120, 'Large': 77},
  'summary': {
    'batches': {'Medium': 2.5, 'Large': 5.25},
    'jars': {'Medium': 300, 'Large': 404},
    'jars_total': 704,
    'items_to_make': 14,
    'needed_now_count': 6,
    'missing_count': 5,
    'blocked_count': 9,
  },
  'branches': [
    {
      'warehouse': 'Nasr city - J',
      'label': 'Nasr city',
      'weekly_sales': 331.5,
      'par_total': 1120,
      'on_hand_total': 222,
      'fill_total': 898,
      'below_backup_count': 7,
    },
    {
      'warehouse': 'Dokki - J',
      'label': 'Dokki',
      'weekly_sales': 120,
      'par_total': 360.0,
      'on_hand_total': 400.0,
      'fill_total': 0,
      'below_backup_count': 0,
    },
  ],
  'items': [
    {
      'item_code': 'Blueberry Large',
      'item_name': 'Blueberry Large',
      'flavour': 'Blueberry',
      'size': 'Large',
      'batch_size': 77,
      'weekly_sales': 55.6,
      'factory_on_hand': 76.0,
      'total_fill': 139,
      'net_need': 63,
      'batches': 1.0,
      'jars': 77,
      'status': 'now',
      'blocked_by': ['Jar Lid 330'],
      'branches': [
        {
          'warehouse': 'Nasr city - J',
          'label': 'Nasr city',
          'weekly_sales': 35.8,
          'par': 108,
          'on_hand': 1.0,
          'fill': 107,
          'days_of_cover': 0.2,
          'below_backup': true,
          'stock_is_negative': false,
        },
        {
          'warehouse': 'Dokki - J',
          'label': 'Dokki',
          'weekly_sales': 19.8,
          'par': 60,
          'on_hand': -4,
          'fill': 32,
          'days_of_cover': null,
          'below_backup': 1,
          'stock_is_negative': 1,
        },
      ],
    },
    {
      'item_code': 'Date Large',
      'item_name': 'Date Large',
      'flavour': 'Date',
      'size': 'Large',
      'batch_size': 77,
      'weekly_sales': 0,
      'factory_on_hand': 12,
      'total_fill': 0,
      'net_need': 0,
      'batches': 0,
      'jars': 0,
      'status': 'no_sales',
      'blocked_by': [],
      'branches': [],
    },
    {
      'item_code': 'Mango Medium',
      'item_name': 'Mango Medium',
      'flavour': 'Mango',
      'size': 'Medium',
      'batch_size': 120,
      'weekly_sales': 40,
      'factory_on_hand': 0,
      'total_fill': 88,
      'net_need': 88,
      'batches': 0.75,
      'jars': 90,
      'status': 'round',
      'blocked_by': [],
      'branches': [],
    },
    {
      'item_code': 'Lotus Medium',
      'item_name': 'Lotus Medium',
      'flavour': 'Lotus',
      'size': 'Medium',
      'batch_size': 120,
      'weekly_sales': 30.2,
      'factory_on_hand': 200,
      'total_fill': 50,
      'net_need': 0,
      'batches': 0,
      'jars': 0,
      'status': 'covered',
      'blocked_by': [],
      'branches': [],
    },
  ],
  'prep': [
    {
      'item_code': 'Butter Biscuit',
      'item_name': 'Butter Biscuit',
      'uom': 'Kg',
      'required': 12.45,
      'on_hand': 0.02,
      'to_make': 12.43,
      'batch_yield': 13.674,
      'batches': 0.91,
      'made_fresh': false,
    },
    {
      'item_code': 'Cheese Mix',
      'item_name': 'Cheese Mix',
      'uom': 'Kg',
      'required': 30,
      'on_hand': 0,
      'to_make': 0,
      'batch_yield': 4.2,
      'batches': 7.2,
      'made_fresh': true,
    },
    {
      'item_code': 'Crumble',
      'item_name': 'Crumble',
      'uom': 'Kg',
      'required': 2,
      'on_hand': 5,
      'to_make': 0,
      'batch_yield': 3,
      'batches': 0,
      'made_fresh': false,
    },
  ],
  'materials': [
    {
      'item_code': 'Jar Lid 330',
      'item_name': 'Jar Lid 330',
      'item_group': 'Packaging',
      'uom': 'Nos',
      'required': 404.0,
      'on_hand': 174.0,
      'alternative_on_hand': 0.0,
      'missing': 230.0,
      'used_by': ['Blueberry Large'],
    },
    {
      'item_code': 'Sugar',
      'item_name': 'Sugar',
      'item_group': 'Raw Material',
      'uom': 'Kg',
      'required': 18.456,
      'on_hand': 40,
      'alternative_on_hand': 0,
      'missing': 0,
      'used_by': ['Mango Medium', 'Blueberry Large'],
    },
  ],
  'notices': ['BOM missing for Date Large'],
};
